// <auto-generated />
using System;
using AirlineSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirlineSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210615084318_TripsPlaneRelation")]
    partial class TripsPlaneRelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AirlineSystem.Models.AirportModel", b =>
                {
                    b.Property<int>("AirportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AirportName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirportShort")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CountryCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirportID");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("AirlineSystem.Models.PassengerModel", b =>
                {
                    b.Property<int>("PassengerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassportNo")
                        .HasColumnType("int");

                    b.HasKey("PassengerID");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("AirlineSystem.Models.PlaneModel", b =>
                {
                    b.Property<int>("PlaneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirportID")
                        .HasColumnType("int");

                    b.Property<int?>("AirportsAirportID")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("PlaneName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaneType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlaneID");

                    b.HasIndex("AirportsAirportID");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("AirlineSystem.Models.TripModel", b =>
                {
                    b.Property<int>("TripNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CabinClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlaneID")
                        .HasColumnType("int");

                    b.Property<int>("PlaneNo")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("RoadType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TakeOffDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("TripNo");

                    b.HasIndex("PlaneID");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("AirlineSystem.Models.PlaneModel", b =>
                {
                    b.HasOne("AirlineSystem.Models.AirportModel", "Airports")
                        .WithMany("Planes")
                        .HasForeignKey("AirportsAirportID");

                    b.Navigation("Airports");
                });

            modelBuilder.Entity("AirlineSystem.Models.TripModel", b =>
                {
                    b.HasOne("AirlineSystem.Models.PlaneModel", "Plane")
                        .WithMany("Trip")
                        .HasForeignKey("PlaneID");

                    b.Navigation("Plane");
                });

            modelBuilder.Entity("AirlineSystem.Models.AirportModel", b =>
                {
                    b.Navigation("Planes");
                });

            modelBuilder.Entity("AirlineSystem.Models.PlaneModel", b =>
                {
                    b.Navigation("Trip");
                });
#pragma warning restore 612, 618
        }
    }
}
