// <auto-generated />
using System;
using KittyCat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KittyCat.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210616121509_dbtables")]
    partial class dbtables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KittyCat.Models.AdopterModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("adopter");

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 42,
                            email = "koko@gmail.com",
                            gender = "male",
                            image = "https://images.unsplash.com/photo-1521119989659-a83eee488004?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=728&q=80",
                            name = "Ken",
                            phone = " 85454995042 "
                        },
                        new
                        {
                            id = 2,
                            age = 30,
                            email = "momo@gmail.com",
                            gender = "female",
                            image = "https://images.unsplash.com/photo-1514448553123-ddc6ee76fd52?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80",
                            name = "Natasha",
                            phone = " 46736437743 "
                        });
                });

            modelBuilder.Entity("KittyCat.Models.CatModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 0)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdopterId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("health")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("AdopterId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OwnerId");

                    b.ToTable("catTable");

                    b.HasData(
                        new
                        {
                            id = 1,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Young",
                            breed = "Domestic Short Hair",
                            description = "SPICE THEMED MOMMA:  2 years old / small\n\nHi, my name is Anise!  I came to Mostly Mutts from animal...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975818/4/?bust=1623845036&width=600",
                            name = "Anise"
                        },
                        new
                        {
                            id = 2,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Long Hair",
                            description = "Han is a bit shy at first, but he loves to be held and is extremely playful. Han is fixed...",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975825/1/?bust=1623844958&width=600",
                            name = "Han"
                        },
                        new
                        {
                            id = 3,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Santos is a sweet little man. He is 12 weeks old, fixed and vaccinated and looking for his forever home.",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975823/1/?bust=1623844812&width=600",
                            name = "Santos"
                        },
                        new
                        {
                            id = 4,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Suki is a sweet and loving lady! She is 12 weeks old and spayed/vaccinated",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975822/1/?bust=1623844732&width=600",
                            name = "Suki"
                        },
                        new
                        {
                            id = 5,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Adult",
                            breed = "Domestic Short Hair",
                            description = "“Hi, my name is Sabrina! I belonged to a small colony that resided at a mechanic shop. I gave birth...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975819/1/?bust=1623844667&width=600",
                            name = "Sabrina"
                        },
                        new
                        {
                            id = 6,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Elena is a sweet little lady. She is playful and outgoing. She loves to be pet and play.\n\nShe is...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975820/1/?bust=1623844640&width=600",
                            name = "Elena"
                        },
                        new
                        {
                            id = 7,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Tabby",
                            description = "You can fill out an adoption application online on our official website.If interested in any of our animals for adoption,...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975811/1/?bust=1623845035&width=600",
                            name = "Qd Litter Pecan"
                        },
                        new
                        {
                            id = 8,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Tabby",
                            description = "You can fill out an adoption application online on our official website.If interested in any of our animals for adoption,...",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975809/1/?bust=1623845060&width=600",
                            name = "Qd Litter Peanutbutter"
                        },
                        new
                        {
                            id = 9,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Tabby",
                            description = "You can fill out an adoption application online on our official website.If interested in any of our animals for adoption,...",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975810/1/?bust=1623845059&width=600",
                            name = "Qd Litter Pistashio"
                        },
                        new
                        {
                            id = 10,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Young",
                            breed = "Domestic Short Hair",
                            description = "Madison and her 4 siblings were born outside in March and rescued in May. She is a little reserved but...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51969350/1/?bust=1623796232&width=600",
                            name = "Madison"
                        },
                        new
                        {
                            id = 11,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Young",
                            breed = "Domestic Short Hair",
                            description = "Joey and his siblings were born in March to an outside Mom and thankfully rescued in May. Joey is the...",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51969376/2/?bust=1623798161&width=600",
                            name = "Joey"
                        },
                        new
                        {
                            id = 12,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Young",
                            breed = "Domestic Short Hair",
                            description = "Cocoa and his 4 siblings were born in March outside and rescued in May. He is a quiet sweet boy...",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51970085/1/?bust=1623798281&width=600",
                            name = "Cocoa"
                        },
                        new
                        {
                            id = 13,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Adult",
                            breed = "Domestic Long Hair",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975792/1/?bust=1623844537&width=600",
                            name = "Davey Jones"
                        },
                        new
                        {
                            id = 14,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Tabby",
                            description = "Elmo was found stray and brought in for adoption.",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975790/1/?bust=1623843810&width=600",
                            name = "Elmo"
                        },
                        new
                        {
                            id = 15,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Cookie Monster was found stray and brought in for adoption.",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975787/1/?bust=1623843759&width=600",
                            name = "Cookie Monster"
                        },
                        new
                        {
                            id = 16,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Young",
                            breed = "Domestic Short Hair",
                            description = "GREY THEMED MOMMA:  2 years old / small\n\nHello, I&#039;m Haze!  I found myself at animal control nursing three 4-week-old...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975786/1/?bust=1623843712&width=600",
                            name = "Haze"
                        },
                        new
                        {
                            id = 17,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Big Bird was found stray and brought in for adoption.",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975785/1/?bust=1623843703&width=600",
                            name = "Big Bird"
                        },
                        new
                        {
                            id = 18,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Archie was found stray and brought in for adoption.",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975782/1/?bust=1623843648&width=600",
                            name = "Archie"
                        },
                        new
                        {
                            id = 19,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Abigail was found stray and brought in for adoption.",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975780/1/?bust=1623843593&width=600",
                            name = "Abigail"
                        },
                        new
                        {
                            id = 20,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Arlo was found stray and brought in for adoption.",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975773/1/?bust=1623843544&width=600",
                            name = "Arlo"
                        },
                        new
                        {
                            id = 21,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Young",
                            breed = "Domestic Medium Hair",
                            description = "Beautiful, sweet friendly Samara was living outside and fed by some kind people in Trenton. She gave birth outside and...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975778/1/?bust=1623844167&width=600",
                            name = "Samara"
                        },
                        new
                        {
                            id = 22,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Adult",
                            breed = "Domestic Short Hair",
                            description = "Emma Ruby is a gentle and good nature cat that was taken into rescue by a fellow rescuer when she...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975776/1/?bust=1623844136&width=600",
                            name = "Emma Ruby"
                        },
                        new
                        {
                            id = 23,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Young",
                            breed = "Domestic Short Hair",
                            description = "SPICE THEMED MOMMA:  2 years old / small\n\nHi, my name is Anise!  I came to Mostly Mutts from animal...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975818/4/?bust=1623845036&width=600",
                            name = "Anise"
                        },
                        new
                        {
                            id = 24,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Long Hair",
                            description = "Han is a bit shy at first, but he loves to be held and is extremely playful. Han is fixed...",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975825/1/?bust=1623844958&width=600",
                            name = "Han"
                        },
                        new
                        {
                            id = 25,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Santos is a sweet little man. He is 12 weeks old, fixed and vaccinated and looking for his forever home.",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975823/1/?bust=1623844812&width=600",
                            name = "Santos"
                        },
                        new
                        {
                            id = 26,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Suki is a sweet and loving lady! She is 12 weeks old and spayed/vaccinated",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975822/1/?bust=1623844732&width=600",
                            name = "Suki"
                        },
                        new
                        {
                            id = 27,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Adult",
                            breed = "Domestic Short Hair",
                            description = "“Hi, my name is Sabrina! I belonged to a small colony that resided at a mechanic shop. I gave birth...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975819/1/?bust=1623844667&width=600",
                            name = "Sabrina"
                        },
                        new
                        {
                            id = 28,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Elena is a sweet little lady. She is playful and outgoing. She loves to be pet and play.\n\nShe is...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975820/1/?bust=1623844640&width=600",
                            name = "Elena"
                        },
                        new
                        {
                            id = 29,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Tabby",
                            description = "You can fill out an adoption application online on our official website.If interested in any of our animals for adoption,...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975811/1/?bust=1623845035&width=600",
                            name = "Qd Litter Pecan"
                        },
                        new
                        {
                            id = 30,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Tabby",
                            description = "You can fill out an adoption application online on our official website.If interested in any of our animals for adoption,...",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975809/1/?bust=1623845060&width=600",
                            name = "Qd Litter Peanutbutter"
                        },
                        new
                        {
                            id = 31,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Tabby",
                            description = "You can fill out an adoption application online on our official website.If interested in any of our animals for adoption,...",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975810/1/?bust=1623845059&width=600",
                            name = "Qd Litter Pistashio"
                        },
                        new
                        {
                            id = 32,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Young",
                            breed = "Domestic Short Hair",
                            description = "Madison and her 4 siblings were born outside in March and rescued in May. She is a little reserved but...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51969350/1/?bust=1623796232&width=600",
                            name = "Madison"
                        },
                        new
                        {
                            id = 33,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Young",
                            breed = "Domestic Short Hair",
                            description = "Joey and his siblings were born in March to an outside Mom and thankfully rescued in May. Joey is the...",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51969376/2/?bust=1623798161&width=600",
                            name = "Joey"
                        },
                        new
                        {
                            id = 34,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Young",
                            breed = "Domestic Short Hair",
                            description = "Cocoa and his 4 siblings were born in March outside and rescued in May. He is a quiet sweet boy...",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51970085/1/?bust=1623798281&width=600",
                            name = "Cocoa"
                        },
                        new
                        {
                            id = 35,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Adult",
                            breed = "Domestic Long Hair",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975792/1/?bust=1623844537&width=600",
                            name = "Davey Jones"
                        },
                        new
                        {
                            id = 36,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Tabby",
                            description = "Elmo was found stray and brought in for adoption.",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975790/1/?bust=1623843810&width=600",
                            name = "Elmo"
                        },
                        new
                        {
                            id = 37,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Cookie Monster was found stray and brought in for adoption.",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975787/1/?bust=1623843759&width=600",
                            name = "Cookie Monster"
                        },
                        new
                        {
                            id = 38,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Young",
                            breed = "Domestic Short Hair",
                            description = "GREY THEMED MOMMA:  2 years old / small\n\nHello, I&#039;m Haze!  I found myself at animal control nursing three 4-week-old...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975786/1/?bust=1623843712&width=600",
                            name = "Haze"
                        },
                        new
                        {
                            id = 39,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Big Bird was found stray and brought in for adoption.",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975785/1/?bust=1623843703&width=600",
                            name = "Big Bird"
                        },
                        new
                        {
                            id = 40,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Archie was found stray and brought in for adoption.",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975782/1/?bust=1623843648&width=600",
                            name = "Archie"
                        },
                        new
                        {
                            id = 41,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Abigail was found stray and brought in for adoption.",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975780/1/?bust=1623843593&width=600",
                            name = "Abigail"
                        },
                        new
                        {
                            id = 42,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Baby",
                            breed = "Domestic Short Hair",
                            description = "Arlo was found stray and brought in for adoption.",
                            gender = "Male",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975773/1/?bust=1623843544&width=600",
                            name = "Arlo"
                        },
                        new
                        {
                            id = 43,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Young",
                            breed = "Domestic Medium Hair",
                            description = "Beautiful, sweet friendly Samara was living outside and fed by some kind people in Trenton. She gave birth outside and...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975778/1/?bust=1623844167&width=600",
                            name = "Samara"
                        },
                        new
                        {
                            id = 44,
                            AdopterId = 1,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "Adult",
                            breed = "Domestic Short Hair",
                            description = "Emma Ruby is a gentle and good nature cat that was taken into rescue by a fellow rescuer when she...",
                            gender = "Female",
                            health = "spayed_neutered",
                            image = "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51975776/1/?bust=1623844136&width=600",
                            name = "Emma Ruby"
                        });
                });

            modelBuilder.Entity("KittyCat.Models.LocationModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("location");

                    b.HasData(
                        new
                        {
                            id = 1,
                            address = "505 broadway st",
                            name = "Vetsreet",
                            phone = "303849244"
                        },
                        new
                        {
                            id = 2,
                            address = "404 broadway st",
                            name = "Pawpatrol",
                            phone = "758348939"
                        },
                        new
                        {
                            id = 3,
                            address = "303 broadway st",
                            name = "smartPet",
                            phone = " 7548484844 "
                        });
                });

            modelBuilder.Entity("KittyCat.Models.OwnerModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("owner");

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 24,
                            email = "roro@gmail.com",
                            gender = "female",
                            image = "https://images.unsplash.com/photo-1508002366005-75a695ee2d17?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80",
                            name = "Rose",
                            phone = " 85454995042 ",
                            reason = "relocating"
                        },
                        new
                        {
                            id = 2,
                            age = 54,
                            email = "jojo@gmail.com",
                            gender = "male",
                            image = "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
                            name = "Jack",
                            phone = " 46736437743 ",
                            reason = "relocating"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("KittyCat.Models.CatModel", b =>
                {
                    b.HasOne("KittyCat.Models.AdopterModel", "Adopter")
                        .WithMany("cats")
                        .HasForeignKey("AdopterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KittyCat.Models.LocationModel", "Location")
                        .WithMany("cats")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KittyCat.Models.OwnerModel", "Owner")
                        .WithMany("cats")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adopter");

                    b.Navigation("Location");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KittyCat.Models.AdopterModel", b =>
                {
                    b.Navigation("cats");
                });

            modelBuilder.Entity("KittyCat.Models.LocationModel", b =>
                {
                    b.Navigation("cats");
                });

            modelBuilder.Entity("KittyCat.Models.OwnerModel", b =>
                {
                    b.Navigation("cats");
                });
#pragma warning restore 612, 618
        }
    }
}
